### ISSUE TITLE
Second Replicaset Member Does Not Configure But 3+ Does

### ISSUE THREAD

**Issue by ekristen** [ekristen/chef-mongodb#1]
Using this as reference  https://github.com/edelight/chef-mongodb/issues/61#issuecomment-9531587

**Comment by ekristen** [comment]
~~Not sure why this is happening but I added in some addition debug information.~~

~~Looks like at the time of adding my second node which my first had been up for a while.~~

~~I'll have to dig deeper on this -- but basically looks like it didn't think that the first node was up.~~

Correction, looks like the second node hasn't started all the way yet, looks like I need to build in some checks. The reason why 3rd and 4th work is because most likely by the time you get to the 3rd and 4th the 2nd one is and the reconfigure works.

> [2012-10-17T16:52:59+00:00] INFO: [node[mongodb01]]
> [2012-10-17T16:52:59+00:00] INFO: ["ip-10-170-21-158.us-west-1.compute.internal"]
> [2012-10-17T16:52:59+00:00] INFO: [node[mongodb01], node[mongodb02]]
> [2012-10-17T16:52:59+00:00] INFO: Configuring replicaset with members ip-10-170-21-158, ip-10-171-10-65
> [2012-10-17T16:52:59+00:00] INFO: Executing replSetReconfig
> [2012-10-17T16:53:00+00:00] WARN: exception: need most members up to reconfigure, not ok : ip-10-171-10-65.us-west-1.compute.internal:27017
> [2012-10-17T16:53:00+00:00] INFO: ruby_block[config_replicaset] called
> [2012-10-17T16:53:01+00:00] INFO: Chef Run complete in 136.237964207 seconds
> [2012-10-17T16:53:01+00:00] INFO: Running report handlers
> [2012-10-17T16:53:01+00:00] INFO: Report handlers complete

**Comment by mbbernstein** [comment]
I got one more problem, the second started a new replica set and the third also.

**Comment by ekristen** [comment]
Not sure how that is possible. Do you have output from mongo? The recipe connects directly to the existing replicaset and reconfigures adding the new ones.

**Comment by mbbernstein** [comment]
Ok.. now I have a few answers...
- 1. When you create the first replicaset, you don't pass the _fqdn_ to the mongo, so it gets the hostname as the host, and than second don't find this one on the run.

https://github.com/ekristen/chef-mongodb/blob/master/libraries/mongodb.rb#L97

Insted of:

```
result = connection['admin'].command({:replSetInitiate => 1}, :check_response => false)
```

Put this:

```
rs_members = []
rs_members << {"_id" => 0, "host" => host_members.first }

cmd = BSON::OrderedHash.new
cmd['replSetInitiate'] = {
    "_id" => name,
    "members" => rs_members
}

result = connection['admin'].command(cmd, :check_response => false)
```
- 2. The problem with the second host is this:

> [initandlisten] connection accepted from 10.122.71.219:35051 #14 (2 connections now open)
> [initandlisten] connection accepted from 10.122.71.219:35052 #15 (3 connections now open)
> [conn14] end connection 10.122.71.219:35051 (2 connections now open)
> [initandlisten] connection accepted from 10.122.71.219:35053 #16 (3 connections now open)
> [conn16] replSet replSetReconfig config object parses ok, 2 members specified
> [conn16] couldn't connect to ip-10-122-71-219.ec2.internal:27017: couldn't connect to server ip-10-122-71-219.ec2.internal:27017
> [conn16] replSet cmufcc requestHeartbeat ip-10-122-71-219.ec2.internal:27017 : 9001 socket exception [6] server [ip-10-122-71-219.ec2.internal:27017]
> **[conn16] replSet replSetReconfig exception: need most members up to reconfigure, not ok : ip-10-122-71-219.ec2.internal:27017**
> [conn16] command admin.$cmd command: { replSetReconfig: { _id: "rs_default", version: 2, members: [ { _id: 0, host: "domU-12-31-38-07-44-64.compute-1.internal:27017" }, { _id: 1, host: "ip-10-122-71-219.ec2.internal:27017" } ] } } ntoreturn:1 keyUpdates:0 locks(micros) W:1 reslen:152 175ms
> [conn16] end connection 10.122.71.219:35053 (2 connections now open)
> [conn15] end connection 10.122.71.219:35052 (2 connections now open)

**Comment by ekristen** [comment]
I think you have old code. I got rid of the replsetconfig you referenced in favor of the method you suggested.

See line 162 https://github.com/ekristen/chef-mongodb/blob/master/libraries/mongodb.rb

**Comment by mbbernstein** [comment]
The problem with the second host, I resolved with a sleep(300), so the problem is that the host is not ready.

**Comment by ekristen** [comment]
Sweet, if you look higher in the code you'll see I have a retries system,
I'll implement that to check that the second one is up.

On Oct 17, 2012, at 5:46 PM, Michael Belfer Bernstein <
notifications@github.com> wrote:

The problem with the second host, I resolved with a sleep(300), so the
problem is that the host is not ready.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ekristen/chef-mongodb/issues/1#issuecomment-9545327.

**Comment by mbbernstein** [comment]
Please look at my code at https://github.com/clicksign-infra/chef-mongodb/commit/0d8f906b7e1e1a958d2c6eecf716e34c25c46d75

**Comment by ekristen** [comment]
My latest commit fixes it all. At least in my tests. It now ensures that the new node is online before trying to reconfigure the replicaset.

**Comment by mbbernstein** [comment]
There is a problem with the line 97:

```
result = connection['admin'].command({:replSetInitiate => 1}, :check_response => false)
```

Mongo takes the **hostname** of the server as a default if no name is explicit pass for the first member.

In AWS EC2, this can be a problem. Imagine that the first server have this hostname and fqdn:

```
hostname: domU-12-31-38-00-B5-0D
fqdn: domU-12-31-38-00-B5-0D.compute-1.internal 
```

And the second one have this:

```
hostname: ip-10-87-27-67
fqdn: ip-10-87-27-67.ec2.internal
```

If the replica set uses just the hostname and not the fqdn, the second host wouldn't find the first one, because they are in diferent domains.

That's way you need to explicit the hostname like this:

```
rs_members = []
rs_members << {"_id" => 0, "host" => host_members.first }

cmd = BSON::OrderedHash.new
cmd['replSetInitiate'] = {
    "_id" => name,
    "members" => rs_members
}

result = connection['admin'].command(cmd, :check_response => false)
```

The diference is this:

```
{
    "_id" : "rs0",
    "version" : 1,
    "members" : [
             {
                     "_id" : 0,
                     "host" : "domU-12-31-38-00-B5-0D:27017"
             }
     ]
}
```

from this:

```
{
    "_id" : "rs0",
    "version" : 1,
    "members" : [
             {
                     "_id" : 0,
                     "host" : "domU-12-31-38-00-B5-0D.compute-1.internal:27017"
             }
     ]
}
```

**Comment by ekristen** [comment]
I follow -- I'm testing it now. The reason it hasn't ever been a problem before is because upon the second node being added it updates with the FQDNs for both.

**Comment by mbbernstein** [comment]
Hi Erik,

Can you make this pull request?

Thanks,

Michael

**Comment by ekristen** [comment]
Actually I have multiple changes I haven't committed that changes a lot of this to work more properly. Let me get those committed, then if you can test and see what happens and then readdress this pull.

**Comment by ekristen** [comment]
@mbbernstein I've commit several changes that in all my testing and deployments make replicasets work properly. Can you confirm?

**Comment by mbbernstein** [comment]
@ekristen I will test this in the next week

## 

Michael

**Comment by mbbernstein** [comment]
Hi @ekristen,

I'm back! I've tested this cookbook many times and seems to be working very well.

Can you make this pull request?

Thanks,

Michael

**Comment by ekristen** [comment]
I am no longer using chef.
